### ISSUE TITLE
Regular Expression and show list item support

### ISSUE THREAD

**Issue by pawansx-22** [rokuality/rokuality-server#12] opened 2019-12-09 20:37 UTC
Soon, I am planning to write a demo Rokuality test for our App. I have gone through the Java example test, and found there is only test for text. Do, rokuality support show/episode list items and time-related information(most probably using regular expression). Do we need to have any special strategy for this, apart from using images from live web service?
Help will be highly appreciated.

**Comment by baclark774** [comment] 2019-12-10 02:03
Sure. So the text based identifiers will look for whatever text is contained within the screen image. Currently you can't pass it an explicit regular expression string as it will process it literally. But if you resolve the regular expression before you pass it then it will work just fine. But a word of caution that it is still bound by the inherit limitations of current OCR technologies. So the more complicated the character string the less likely you are to find an exact match during your locator searches. I would definitely recommend setting up a Google Vision account and using the Google Vision OCR module instead of the default Tesseract in that case. 

In regard to show/list items - yes you can search for those as text strings in the same fashion as mentioned above. Typically the projects that use this solution now will use an http client in their test to first query their application back end feeds to get the expected show/episode content and then pass those values to the Rokuality test to verify that the content is available as expected.

In regard to image locators - those can be a bit trickier than the text based locators as you have to ensure that the image snippet is an apples to apples comparison with the expected vs actual screen. And many modern apps have background images or overlays that change and may cause an issue depending on the app/scenario.

We're bound by the limitations of the technology but you can do some really powerful automation if you play with it a bit. We have projects that have hundreds of tests using this solution that run against multiple builds daily with 100% reliability. It can take a bit more work than technologies that offer native based automation tools like android uiautomator or apple xcuitest but if you spend some time you can achieve solid test reliability in the same fashion.

Let me know if you have any questions as you get going and I'll be happy to help point you in the right direction.

**Comment by pawansx-22** [comment] 2019-12-10 20:23
Many thanks for support and guidance, I have started to integrate Rokuality with our existing project. As I see ideas that you provided, are quite practical for our implementation, I would also like to know what is recommended way to determine a specific element which is already located above mentioned strategy is "focused" and navigating to a element(Which could be show/episode list item or a link) which is already located, via roku-remote button and pressing "Select" button. Soon, I will be writing a script, then I will be keeping this in mind.

**Comment by baclark774** [comment] 2019-12-11 15:35
So it gets a little tricky when trying to auto focus on an element as it's hard to know the current focus location of the remote. You kind of have to keep track of it procedurally as your test moves through its flow. Each locator match will give you back the location object of where it's at on screen, so if you got creative you could write a method that keeps track of your x,y location anytime you perform a remote control action - and then create a wrapper method that handles auto focus to a found element. But most projects follow some type of popular test design model like the page/view/journey pattern which wraps up all their UI actions and takes care of handling UI traveling through their apps.

Platforms like xcuitest for tvos make it easy with their focus api method which will automatically do this for the user. But in this case Roku doesn't give us any native rich document model to take advantage of unfortunately.

**Comment by pawansx-22** [comment] 2019-12-11 19:26
Thanks for your generosity. Rokuality fits well within our framework. From tomorrow, I will start to play with it. Yes, I want to have our implementation in page/view/journey pattern, but I would like to keep our implementation in appium flavor as much as possible. Above you said "if you got creative you could write a method that keeps track of your x,y location anytime you perform a remote control action", I have a question how to achieve this as I don't know remote will be pointing to which element especially in case of show/episode list items, which is dynamically located. Further, I don't want to image locators because OCR limitations as you mentioned, which could be troublesome in case of our app, so that I could determine any change in any specific element. So, there is suggestion for tracking x,y location after/before performing any remote device.

**Comment by pawansx-22** [comment] 2019-12-11 23:46
I think I have big problem here as We do not have a sideloadable zip file here. Can we launch our app/channel passing listed app id as app desired cap after adding a channel?

**Comment by baclark774** [comment] 2019-12-12 13:33
So as of right now you have to have a sideloadable zip. An underlying limitation of the roku api is that it only captures images from the sideloaded dev packages. I would check with the developers of your channels as they should hopefully be able to easily provide those.

Also we currently have an update that will roll out sometime later next week which will allow you to test against an already installed production channel on a device. But it requires an hdmi capture card be connected from your Roku to your machine running the server. See the readme section on hdmi capture cards and why we use them as this will operate similarly with those caps. It's the only way to bypass the Roku dev restriction against capturing images from the device from channels that aren't sideloaded.

**Comment by pawansx-22** [comment] 2019-12-12 15:55
Thanks for your prompt support. Because of our operational structure, we need production first implementation, though tests will be run against regular builds, too. So, I am eagerly waiting for the feature to run test on a production channel and then, I will start writing test.

I think, as application is launched, we can initiate a remote action, to check which element is pointing then from there, we can get x,y location after every remote action. If you will have any thought/suggestion in coming days regarding this problem, please share.

Any way, thank you very much.

**Comment by baclark774** [comment] 2019-12-21 21:11
Pleased to say that testing a production roku channel is now possible in the latest 1.2.3 release:

https://rokualitypublic.s3.amazonaws.com/rokuality-server-1.2.3.jar

Note that it does require an HDMI capture card connected between the Roku and the machine running the server. See the Readme section on capture cards as there are 2 tested capture cards but many others will work. To test a production Roku channel you'll need to pass the following capabilities at session start:

// id of the installed production channel to launch.
// can be found via curl http://your_roku_ip_address:8060/query/apps
capabilities.addCapability("App", "the id of the installed channel you wish to launch");

// the video and audio inputs of your capture card connected to your Roku
// can be found via:
// MAC: ~/Rokuality/dependencies/ffmpeg_v4.1 -f avfoundation -list_devices true -i ""
// WINDOWS: ~\Rokuality\dependencies\ffmpeg_win_v4.1\bin\ffmpeg.exe -list_devices true -f dshow -i dummy

capabilities.addCapability("VideoCaptureInput", "the video input of your capture card");
capabilities.addCapability("AudioCaptureInput", "the audio input of your capture card");

**Comment by baclark774** [comment] 2019-12-21 21:13
Also wanted to mention that we are hard at work on implementing the brand new Roku Webdriver api's into the server and all supported language bindings:

https://developer.roku.com/docs/developer-program/dev-tools/automated-channel-testing/web-driver.md

Will be available by the first of the year!

**Comment by pawansx-22** [comment] 2019-12-21 21:27
Thanks for your amazing work. Btw, I had played with example app you provided and think, we are good to go.

**Comment by pawansx-22** [comment] 2020-01-01 19:34
Hello, greetings for new year. Have you released Roku WebDriver implementation, as I can see you have merged few commits about it.
Another question about Roku Cloud, that you guys have informed to launch this month, like live/production channel support, traffic dump for analytics test, device matrix etc.

**Comment by baclark774** [comment] 2020-01-02 02:18
Hello. Yes RokuWebDriver support was released in server version 1.2.4 and all subsequent bindings have been updated to support this server version. The documents have all been updated as well as the example tests,  but the key pieces are using the RokuBy locators of text,tag,attribute which will use the native based locators instead of the ocr/image based locators. An example in java would be:

`rokuDriver.finder().findElement(RokuBy.Attribute("attribute", "attributevalue");`

The new media player api is also now exposed to get details about the media playback in flight:

`rokuDriver.info().getMediaPlayerInfo();`

And you can get the native xml document source via:

`rokuDriver.screen().getPageSource();`

In regard to the cloud service - yes we are still slated to launch end of this month with details to come soon!

**Comment by pawansx-22** [comment] 2020-01-02 22:04
Hello,

I am trying to play our production channel. But, when I am running the command
~/Rokuality/dependencies/ffmpeg_v4.1 -f avfoundation -list_devices true -i ""
gives

ffmpeg version 4.1-tessus  https://evermeet.cx/ffmpeg/  Copyright (c) 2000-2018 the FFmpeg developers
  built with Apple LLVM version 10.0.0 (clang-1000.11.45.5)
  configuration: --cc=/usr/bin/clang --prefix=/opt/ffmpeg --extra-version=tessus --enable-avisynth --enable-fontconfig --enable-gpl --enable-libaom --enable-libass --enable-libbluray --enable-libfreetype --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libmysofa --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopus --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-version3 --pkg-config-flags=--static --disable-ffplay
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
[AVFoundation input device @ 0x7ff14fd00dc0] AVFoundation video devices:
[AVFoundation input device @ 0x7ff14fd00dc0] [0] USB Camera
[AVFoundation input device @ 0x7ff14fd00dc0] [1] FaceTime HD Camera
[AVFoundation input device @ 0x7ff14fd00dc0] [2] Capture screen 0
[AVFoundation input device @ 0x7ff14fd00dc0] AVFoundation audio devices:
[AVFoundation input device @ 0x7ff14fd00dc0] [0] Unknown USB Audio Device
[AVFoundation input device @ 0x7ff14fd00dc0] [1] MacBook Air Microphone
: Input/output error

I have tried all combination for "VideoCaptureInput" and "AudioCaptureInput" using values mentioned above, but getting this error:
com.rokuality.core.exceptions.SessionNotStartedException: Failed to initiate hdmi driver! Is the device connected via an hdmi capture card and are the VideoCaptureInput and AudioCaptureInput capabilities correct? See the server README for details of how to obtain those cap values.

Again, I tired to create Roku Driver with  "App" capability alone, app is getting launched correctly, but I getting this error:

com.rokuality.core.exceptions.SessionNotStartedException: Failed to start image collection on the device! Is the device provisionsed properly for test and listening at 192.168.0.4

I have one question, since Roku WebDriver provide access to native element, so, why do we need a hdmi capture card for image capturing?

Please help!

**Comment by baclark774** [comment] 2020-01-02 23:38
What's the hdmi to usb capture card you have attached to your device? Can you include a link to it so I can see the specs. From the above it doesn't look like any of the ones we tested against that are listed in the docs. Based on the output above I'm guessing your caps would be something like the following:
```
// java
caps.add("VideoCaptureInput", "Capture Screen 0");
caps.add("AudioCaptureInput", "Unknown USB Audio Device");
```
Also, you should have a ~/Rokuality/logs directory. Can you zip that up and include it so I can help debug?

We only require hdmi capture cards for production channel testing. Because the roku dev api will only let us capture the screen from a sideloadable dev channel. The reason we require a valid image capture is because this software predates the new roku webdriver api from a time when the only way to test against a roku app was with OCR and image recognition. Also the Roku webdriver api doesn't offer any functionality for getting the device screen. And many Roku channels (depending on how they were built) still won't have an xml page source for native based object testing to work against. And you aren't able to test image content or text within images with the Roku webdriver api but with our solution you can do all of the above.

**Comment by pawansx-22** [comment] 2020-01-03 00:05
This is the capture card(a low cost, just bought it for experiment), I am using right now:

https://www.amazon.in/gp/product/B07B9Q7792/ref=ppx_yo_dt_b_asin_title_o03_s00?ie=UTF8&psc=1

If you find this unsuitable, please send me an Amazon India link for a HDMI capture device having proper specs to run the rokuality test, so that I could get it.

I have used these capability:

capabilities.addCapability("VideoCaptureInput", "Capture Screen 0");
capabilities.addCapability("AudioCaptureInput", "Unknown USB Audio Device");

Please find logs.zip
[https://drive.google.com/open?id=1cBi-oMHPqqfWjW33cIszFqUR9N0GqR1i]

2020-01-03 05:29:29.297  WARN log - Failed to capture video/audio indexes!

Thanks for your support.

**Comment by baclark774** [comment] 2020-01-03 02:38
Can you try the following:
```
capabilities.addCapability("VideoCaptureInput", "Capture screen 0");
capabilities.addCapability("AudioCaptureInput", "Unknown USB Audio Device");
```
It's case sensitive on the index filter. Want to make sure that's exact. Also adding better logging to this to help determine the cause.

**Comment by baclark774** [comment] 2020-01-03 16:40
Also can you try this new build?
https://rokualitypublic.s3.amazonaws.com/rokuality-server-1.2.4-hdmi-updates.jar
It adds better logging and detection of the capture index when using the usb capture method. I can't speak to that exact capture card you provided but are you able to view the capture stream manually when using it? For example can you open quicktime and choose 'new movie recording' and then select the inputs to view your roku screen? If you can then the capture card should work. If you can't then it's likely not going to.

I ran this build through all of our roku tests using the 3 different capture cards below and they all worked. 2 of them are low cost capture cards (less than 100$) that seem to work just fine:

https://www.amazon.com/Capture-Broadcast-Nintendo-Consoles-Camcorder/dp/B07HK5NTL8/ref=sr_1_5?keywords=USB+3.0+HD+Capture&qid=1578069550&sr=8-5
https://www.amazon.com/Capture-Broadcast-Streaming-Grabber-Converter/dp/B0779ZJZX3/ref=sr_1_3?keywords=hdmi+usb+capture+cards&qid=1571405168&sr=8-3
https://www.magewell.com/products/usb-capture-hdmi-gen-2

**Comment by pawansx-22** [comment] 2020-01-03 19:34
Yes, my capture card is able to quick player with Video Input as "USB Camera" or "USB Camera #2" depending on which USB port, in which is plugged in and Audio Output "Unknown USB Audio Device". Rokuality is getting this value correctly, connecting to device.

Thanks to your excellent log messages, I found out following command is not working correctly, behind the scene:
nohup /Users/pawan/Rokuality/dependencies/ffmpeg_v4.1 -f avfoundation -framerate 20 -i "0:0" /Users/pawan/Rokuality/temp/videocapture_c31040cb-2f96-4d2c-ac34-bee889eed1aa.mkv

-framerate 20 is problematic here, for my device, as this framework is not supported by my capture card, instead framerate should be 60

So, when I run the command locally:
/Users/pawan/Rokuality/dependencies/ffmpeg_v4.1 -f avfoundation -framerate 30 -i "0:0" /Users/pawan/Rokuality/temp/videocapture_c31040cb-2f96-4d2c-ac34-bee889eed1aa.mkv
it produces error output as following:

ffmpeg version 4.1-tessus  https://evermeet.cx/ffmpeg/  Copyright (c) 2000-2018 the FFmpeg developers
  built with Apple LLVM version 10.0.0 (clang-1000.11.45.5)
  configuration: --cc=/usr/bin/clang --prefix=/opt/ffmpeg --extra-version=tessus --enable-avisynth --enable-fontconfig --enable-gpl --enable-libaom --enable-libass --enable-libbluray --enable-libfreetype --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libmysofa --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopus --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-version3 --pkg-config-flags=--static --disable-ffplay
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
[avfoundation @ 0x7f9de0005400] Selected framerate (20.000000) is not supported by the device
[avfoundation @ 0x7f9de0005400] Supported modes:
[avfoundation @ 0x7f9de0005400]   1920x1080@[60.000240 60.000240]fps
0:0: Input/output error

But, when I run command with framerate 60 as follow:
/Users/pawan/Rokuality/dependencies/ffmpeg_v4.1 -f avfoundation -framerate 60 -i "0:0" /Users/pawan/Rokuality/temp/videocapture_c31040cb-2f96-4d2c-ac34-bee889eed1aa.mkv
is working correctly.

So, can you please provide some insight into how is this solution working with image capturing in background.

Anyway, I will get one of capture card that you have mentioned above as my capture card has one HDMI out port, too apart from HDMI in port, unlike the capture card you are working with.

Main error:
2020-01-04 00:24:58.021  INFO log - Starting video capture for session c31040cb-2f96-4d2c-ac34-bee889eed1aa with command: nohup /Users/pawan/Rokuality/dependencies/ffmpeg_v4.1 -f avfoundation -framerate 20 -i "0:0" /Users/pawan/Rokuality/temp/videocapture_c31040cb-2f96-4d2c-ac34-bee889eed1aa.mkv
2020-01-04 00:25:13.100  INFO log - Failed video capture start for session c31040cb-2f96-4d2c-ac34-bee889eed1aa with output: 

Thanks.

Logs.zip [https://drive.google.com/open?id=1cBi-oMHPqqfWjW33cIszFqUR9N0GqR1i](url)

**Comment by baclark774** [comment] 2020-01-03 20:01
Interesting. When we were initially developing this we were trying to find a good balance between quality and video capture performance since the larger the file the longer it takes the video segments to be evaluated if the user performs an OCR or image evaluation against the device screen. But this should be a capability the user can pass to decide for themselves anyways. Easy enough to fix:

https://rokualitypublic.s3.amazonaws.com/rokuality-server-1.2.4-usb-hdmi-2.jar

And then add the following capability on start:
`caps.addCapability("VideoCaptureFrameRate", 60);`

This will be included in the next official release.

**Comment by pawansx-22** [comment] 2020-01-03 22:29
Thanks, for this build. App is launched few times, few times not. As, capture card is not supporting format, the above command is trying to use. When, driver instance is created successfully, there are two session, one by one, older one is orphaned. So, any element is not located, by Ocr or by roku webdriver.
Since, this solution is quite new too me, I can't much about it. I will get a new capture card, meanwhile I will try to play with the tool.
Thanks.

**Comment by pawansx-22** [comment] 2020-01-06 19:02
I have not worked much on this, But, it will really helpful, if you can share your view on this issue. RokuDriver instance always starts in other than, my current TestNG execution thread.

**Comment by baclark774** [comment] 2020-01-07 11:46
Sounds like maybe more of a testng question or an issue with your executor? If you want to share your test code i may be able to help point you in the right direction. But have you tried running the hdmi roku example test as is?

https://github.com/rokuality/rokuality-java/blob/master/src/test/java/com/rokuality/test/tests/RokuTests.java

With surefire you could run just this test via the following command (note you'll need to change the video/audio caps to your capture card specs):
`mvn -Dtest=RokuTests#findElementWithHDMICaptureTest test`

**Comment by pawansx-22** [comment] 2020-01-07 13:32
Have some driver conflicts with existing drivers with my configuration, not related to this rokuality-java.

Thanks.

**Comment by pawansx-22** [comment] 2020-01-17 18:48
I am able to run roku tests, within our existing framework, on temporary basis. Elements were getting located using Roku WebDriver, for example app provided. But, when I trying to locate an element on several production channels including youtube.

As page source, I am getting this from every production channel:

Code-
String pageSource = rokuDriver.screen().getPageSource();
System.out.println(pageSource);

Output-
 <?xml version="1.0" encoding="UTF-8" ?>
<app-ui>
	<status>FAILED</status>
	<error>Not authorized</error>
</app-ui>

We have asked for a sideloadable zip from developers, so can we proceed with it. But, if a production channel has a valid XMLsource, then, roku webdriver is meant to work?

**Comment by baclark774** [comment] 2020-01-17 18:53
Unfortunately not... A limitation of the underlying roku implementation. They prevent automation against anything that isn't a sideloaded dev channel. If you wish to test against a production channel you'd have to use the hdmi to usb capture card option and then the RokuBy webdriver locators would not work but the OCR/Image based locators (By.Text and By.Image) would still work.

**Comment by pawansx-22** [comment] 2020-01-20 15:40
I have raised an issue regarding automation of production channels here,

[https://github.com/rokudev/automated-channel-testing/issues/3#issuecomment-576298188
](url)
"Your device should have similar dev-id as a package of the production channel ."

I don't have a sideloadable zip yet, so, my question is:
Is Rokuality going to support this feature out of box?

**Comment by baclark774** [comment] 2020-01-20 15:54
Hi @pawansx-22  
Unfortunately if the Roku Webdriver doesn't support production channel testing there's not much we can do other than providing the capture card production channel alternative outlined above :-(

If they ever provide support we'll be the first to implement! But right now we offer the capture card solution as the only known available option for Roku production channel testing.

**Comment by pawansx-22** [comment] 2020-01-20 16:03
Thanks for reply, I just wanted to know, if we have dev-id of the production channel, then we can add the following capabilities:

capabilities.addCapability("DeviceUsername", "PACKAGE_DEV_ID");
capabilities.addCapability("DevicePassword", "1234");

or, any similar capability.

I dont know much about it, but, I am just passing my idea.

**Comment by baclark774** [comment] 2020-01-20 16:09
Unfortunately not. I just left a post on that message thread asking to elaborate but i'm pretty positive it's not possible to run Roku WebDriver against a pre-installed production channel in any capacity.

**Comment by pawansx-22** [comment] 2020-01-20 16:11
Thanks for going an extra mile for this. As soon as we will get a sideloadable zip, I will resume my work with rokuality. I just asked this out of curiosity.

**Closed** 2020-01-24 01:42 UTC
